site_name: Guia de usuario APP
repo_url: https://github.com/vzquezgm/user-guide/settings/pages
repo_name: GitHub
nav:
  - Inicio: index.md
  - Sobre nosotros: about.md
theme: 
  name : material
  language: es
  favicon: favicon.webp
  icon:
    logo: fontawesome/brands/gitlab
