site_name: Guia de usuario APP
repo_url: https://github.com/vzquezgm/user-guide
repo_name: Repositorio GitHub
edit_uri: edit/main/docs/
nav:
  - Inicio: index.md
  - Introducción: 0.Introducción.md
theme: 
  name : material
  language: es
  favicon: favicon.webp
  icon:
    logo: fontawesome/brands/gitlab

# Se agrega la extensión de snippets para incluir fragmentos de código en los documentos #
markdown_extensions:
  - pymdownx.snippets

# Se agrega MathJax para renderizar fórmulas matemáticas #

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js