name: Deploy Documentation
on:
  push:
    branches:
      - main  # O la rama que desees usar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install MkDocs and GitHub Pages
      run: |
        pip install mkdocs mkdocs-material ghp-import
    - name: Build and deploy
      run: |
        mkdocs build
        ghp-import -n -p -b gh-pages site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
